//加入AT89X51.H檔。
#include <AT89X51.H>
//設定掃描動作。
unsigned short led57_scan[5]={0xef,0xf7,0xfb,0xfd,0xfe};
//5x7矩陣顯示資料。
unsigned short led57_valu[4][5]={	{0x24,0x24,0x28,0x70,0x28},
									{0x38,0x38,0x28,0xff,0x28},
									{0x18,0x18,0xff,0xff,0x18},
									{0x47,0x49,0x49,0xff,0x41}};
//宣告延遲函數。
void delay(int del)
{
  long d;
  for(d=0;d<del;d++)
  {
    ; 
  } 
}
//主程式。
int main()
{
//宣告value指定文字，scan為選定掃描用，
//i為回圈控制，shy為閃爍控制，x是指撥開關記錄。
  unsigned int value=0,shy=0,scan=0,i=0,x;
//為了不斷執行，用無窮迴圈包住。
  while(1)
  {
//先向指撥讀取鍵值。
    x=P1;
//判斷被要求要顯示哪一個項目。
//如果為SWITCH為0000_0010的話，執行文字逐一顯示。
    if(x==0x02)
    {
//延遲一會兒。
      delay(64);
//i不斷+1，作為每個顯示文字之停留間隔。
      i++;
//如果i整除500的話，換至下一個文字。
      if(i%500==0)
      {
//改變value，顯示下一個文字。
        value++;
      }
//如果超出預設的顯示範圍，則修正。
      if(value>3)
      {
//初始value值，使其動新顯示。
        value=0;
      }
//P2根據scan輸出掃描訊號。
      P2=led57_scan[scan];
//P3根據所指定的陣列顯示資料。
      P3=led57_valu[value][scan];
//累加scan，顯示下一筆資料。
      scan++;
//如果超出預設的掃描範圍，則修正。
      if(scan>4)
      {
 //初始scan值，使其動新掃描。
        scan=0;
      }
    }
//如果為SWITCH為0000_0001的話，執行閃爍顯示。
    else if(x==0x01)
    {
//延遲一會兒。
      delay(64);
//i不斷+1，作為每個顯示之停留間隔。
      i++;
//如果i整除500的話，換至下一個部分。
      if(i%100==0)
      {
//此時如果是全亮則設為全暗，全暗刪設為全亮。
        shy=0xff-shy;
      }
//P2根據scan輸出掃描訊號。
      P2=led57_scan[scan];
//P3輸出shy資料。
      P3=shy;
//累加scan，顯示下一筆資料。
      scan++;
//如果超出預設的掃描範圍，則修正。
      if(scan>4)
      {
 //初始scan值，使其動新掃描。
        scan=0;
      }
    }
  }
}